pidfile /run/chrony/chronyd.pid
driftfile /var/lib/chrony/drift
local stratum 10
allow 192.168.10.0/24
allow 10.0.10.0/24
allow 10.100.10.0/24
allow 10.100.20.0/24
allow 10.100.30.0/24
bindaddress 0.0.0.0
port 123
cmdport 0
logdir /var/log/chrony
