global(workDirectory="/run/rsyslog")
module(load="imudp")
input(type="imudp" port="514" ruleset="remote")

template(
  name="RemoteFile"
  type="string"
  string="/var/log/remote/%fromhost-ip%/events.log"
)

ruleset(name="remote") {
  action(
    type="omfile"
    dynaFile="RemoteFile"
    createDirs="on"
    dirCreateMode="0750"
    fileCreateMode="0640"
  )
  stop
}
