DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
CompressLocalDatabase no
ConnectTimeout 15
ReceiveTimeout 60
MaxAttempts 2
ScriptedUpdates yes
LogTime yes
LogRotate yes
